# OpenFermion Gran Canonical

A diferencia de FermionicML, donde se trabaja en el canónico, la idea es implementar las matrices densidad de 1 y 2 cuerpos en el ensamble canónico, utilizando para ello operadores dados por OpenFermion, por la facilidad de generar los operadores (rhoKarrays) tomando la get_sparse_operator sobre la base. 

In [188]:
# CONFIG
d = 3 # número de niveles

In [215]:
import numpy as np
import openfermion as op
from tqdm import tqdm
from itertools import combinations
from openfermion.utils import commutator, count_qubits, hermitian_conjugated

# Generación de base

class fixed_basis:
    @staticmethod
    def int_to_bin(k, d):
        return np.base_repr(k, 2).zfill(d)

    @staticmethod
    def bin_to_op(b):
        tups = [(i, 1) for i, k in list(enumerate(list(b))) if k == '1']
        return op.FermionOperator(tups)

    def create_basis(self, d):
        basis = []
        for k in range(0,2**d):
            b = self.int_to_bin(k, d)
            oper = self.bin_to_op(b)
            basis.append(oper)
        return basis

    def __init__(self, d):
        self.d = d
        self.base = self.create_basis(d)
        self.size = 2**d-1
        self.canonicals = np.eye(self.size+1)
        self.rho_1_arrays = self.rho_1_arrays_gen(self.base)

    @staticmethod
    def bdb(i, j, d):
        return op.FermionOperator(((i,1),(j,0)))

    def rho_1_arrays_gen(self, base):
        mat = np.zeros((self.d, self.d, self.size, self.size), dtype=object)
        for i in range(0, d):
            for j in range(0, d):
                oper = op.get_sparse_operator(self.bdb(j, i, self.d), n_qubits=d)
                for l in range(1, self.size):
                    for m in range(1, self.size):
                        mat[i,j,l,m] = self.base[1]
        return mat


#bbb = fixed_basis(d).rho_1_arrays
i,j = 1, 2
base = fixed_basis(d).base
cano = fixed_basis(d).canonicals
OPNUM = 2
wfc = base[OPNUM]
idx = cano[OPNUM]
print(idx, wfc)
OPME = fixed_basis.bdb(j, i, d)
print(op.get_sparse_operator(OPME, n_qubits=d))

#print(wfc)
mean_val = lambda x: np.real(np.transpose(idx) @ np.transpose(op.get_sparse_operator(x, n_qubits=d)) @ idx)

print(mean_val(fixed_basis.bdb(j, i, d)))
#print(fixed_basis.bdb(j, i, d))
#print(op.get_sparse_operator(fixed_basis.bdb(j, i, d), n_qubits=d))
#op.linalg.expectation(fixed_basis.bdb(j, i, d), state=op.get_sparse_operator(base[1], n_qubits=d))
print(base[6], base[5])

[0. 0. 1. 0. 0. 0. 0. 0.] 1.0 [1^]
  (1, 2)	(1+0j)
  (5, 6)	(1+0j)
0.0
1.0 [0^ 1^] 1.0 [0^ 2^]


In [168]:
print(base, cano)

[1.0 [1^ 0^], 1.0 [0^], 1.0 [1^], 1.0 []] [[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]
